query GetFiles($id: UUID!) {
    getVersion(id: $id) {
        neededFiles(download: false, full: true) {
            baseUri
            files
        }

        groups {
            standard {
                groupType
                name
                options {
                    name
                    description
                    gamePaths
                    imagePath
                }
            }

            imc {
                groupType
                name
                options {
                    name
                    description
                }
            }
        }
    }
}
