query GetMod($id: UUID!) {
    package(id: $id) {
        id
        name
        tagline
        description
        downloads

        user {
            id
            username
        }

        images {
            id
            displayOrder
        }

        variants {
            id
            name

            versions {
                id
                version
                changelog
                downloadSize
                installSize
                downloads
            }
        }
    }
}
