query GetMe {
    me {
        # for ui
        username

        # for storage calculations
        storageTier {
            totalSize
        }
        usedStorage
        additionalStorage
        hashes
    }
}
